### ISSUE TITLE
server clash because of aes block not full

### ISSUE THREAD

**Issue by lucheng0127** [lucheng0127/virtuallan#9]
```
panic: crypto/cipher: input not full blocks

goroutine 1 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0xb26200?, {0xc00090c010?, 0xc00090c000?, 0x10?}, {0xc00090c010?, 0x10?, 0xc0
0004a800?})
	/usr/local/go/src/crypto/cipher/cbc.go:145 +0x411
github.com/lucheng0127/virtuallan/pkg/cipher.(*AESCipher).Decrypt(0x411e85?, {0xc00090c000, 0x1a2, 0xffff})
	/root/workspaces/virtuallan/pkg/cipher/aes.go:84 +0xd8
github.com/lucheng0127/virtuallan/pkg/packet.Decode({0xc00090c000, 0x1a2, 0xffff})
	/root/workspaces/virtuallan/pkg/packet/proto.go:77 +0xd9
github.com/lucheng0127/virtuallan/pkg/server.(*Server).ListenAndServe(0xc0000f8d20)
	/root/workspaces/virtuallan/pkg/server/conn.go:230 +0x258
github.com/lucheng0127/virtuallan/pkg/server.Run(0xc0003506e0?)
	/root/workspaces/virtuallan/pkg/server/server.go:125 +0x409
github.com/urfave/cli/v2.(*Command).Run(0xc0003506e0, 0xc0003da5c0, {0xc0003d7890, 0x3, 0x3})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*Command).Run(0xc000350f20, 0xc0003da500, {0xc000024080, 0x4, 0x4})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xc2e
github.com/urfave/cli/v2.(*App).RunContext(0xc0003a1c00, {0xb26918?, 0xf1dc60}, {0xc000024080, 0x4, 0x4})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/root/workspaces/virtuallan/main.go:20 +0x53b
```

**Comment by lucheng0127** [comment]
Check [data length]/16 == 0, if not return error(block size 128 bits)
find out why data lose later

**Comment by lucheng0127** [comment]
https://github.com/lucheng0127/virtuallan/pull/10
